### ISSUE TITLE
Artifakt nicht verfügbar

### ISSUE THREAD

**Issue by TheDomCraft** [thenilsdev/discord-ticket-support#181]
Sobald ich das projekt in IntelliJ IDEA Lade bekomme ich den error "Could not find artifact io.nilsdev.discordticketsupport:common:pom:2.0.4 in jcenter (https://jcenter.bintray.com)" und kann nicht fortfahren

**Comment by thenilsdev** [comment]
Damit das Projekt unter IntelliJ erfolgreich lädt musst du `-Dsemantic-release.skip=true` als zusätzliches Maven Argument in den Build Settings (Build, Execution, Deployment | Build Tools | Maven) festlegen
